### ISSUE TITLE
Null pointer exception parsing Kotlin files

### ISSUE THREAD

**Issue by rpau** [openrewrite/rewrite-kotlin#108]
There is a null pointer exception parsing a kotlin file
```
* What went wrong:
Execution failed for task ':service:moderneAst'.
> java.lang.RuntimeException: org.openrewrite.internal.RecipeRunException: Exception while visiting project file 'DashBoard.kt', caused by: java.lang.NullPointerException: Cannot invoke "org.openrewrite.java.tree.Statement.getPrefix()" because "this.statement" is null, at org.openrewrite.kotlin.tree.K$StatementExpression.getPrefix(K.java:822)
```
I also thought that we were not throwing exceptions if there are parsing errors. Is this something that needs to be reviewed?

**Comment by knutwannheden** [comment]
AFAICT the `RecipeRunException` exceptions are handled correctly by the parser. If this is still a problem I instead suspect a problem in the Gradle plugin. Closing this for now.
