### ISSUE TITLE
KotlinPrinter does not print the class FQN on java static import.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#114]
```java
    @Test
    void addJavaStaticImport() {
        rewriteRun(
          spec -> spec.recipe(toRecipe(() -> new AddImport<>("org.junit.jupiter.api.Assertions", "assertFalse", false))),
          kotlin(
            """
              class Foo
              """,
            """
              import org.junit.jupiter.api.Assertions.assertFalse
              class Foo
              """
          )
        );
    }
```

Note: The FQN is intentionally not printed because the `inline` modifier does not exist on `JavaType`. The FQN cannot be printed by the `KotlinPrinter` on `inline` imports otherwise the import will not be recognized.

The Java recipe `AddImport` only supports `Java`, so we may need a `KotlinAddImport` or to improve `AddImport` to support other languages. An additional open issue related to `AddImport` is https://github.com/openrewrite/rewrite-kotlin/issues/54.

Java's `ImportLayoutStyle` does not support other languages well. A `static` block is required by the style but does not exist in every extension of `J` (Kotlin, Python, TS/JS).

**Comment by traceyyoshima** [comment]
This issue is caused by custom printing required for importing Kotlin inline functions, which does not apply to imports of statics from Java classes. Printing may be customized through markers, but the imports added by `AddImport` for Kotlin inline functions and Java static classes, are currently indistinguishable. We plan to add support for mix-ins to improve support for other languages, which should simplify fixing this issue. So, this issue is on hold until the feature is implemented.

**Comment by knutwannheden** [comment]
@traceyyoshima I think we can close this one now, what do you think?

**Comment by traceyyoshima** [comment]
> @traceyyoshima I think we can close this one now, what do you think?

Apologies, I am finally going through the log and just saw this. Closing issue as fixed, thank you so much!
