### ISSUE TITLE
Parsing issue: whitespace in packages and imports is not preserved.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#116]
```java
    @Test
    void pkg() {
        rewriteRun(
          kotlin("package foo . bar")
        );
    }

    @Test
    void kotlinImport() {
        rewriteRun(
          kotlin("import kotlin . collections . List")
        );
    }
```

The LST element is created with the string value from `FqName,` which does not preserve whitespace.

**Comment by traceyyoshima** [comment]
Note: this is a low priority since it is unlikely to happen in the source code.

**Comment by traceyyoshima** [comment]
Update: this will likely be simple using the PSI tree.

**Comment by knutwannheden** [comment]
@traceyyoshima Is the idea that we everywhere traverse the PSI tree instead of the FIR? That would indeed make this simpler, but I am unsure what the plan is here.
