### ISSUE TITLE
Parsing error: java.lang.IllegalStateException: Unexpected single block expression

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#159]
Requires discovery. Reference the data-table produced by `org.openrewrite.FindParseFailures`.

Note: https://github.com/openrewrite/rewrite-kotlin/issues/157 might fix this error, so we should fix 157 first and recheck the results.

**Comment by knutwannheden** [comment]
Closing this issue for now, as we don't have any corresponding test cases. I leave the exceptions in the parser, so if we discover this again, we can investigate.
