### ISSUE TITLE
trailing semicolon parsing

### ISSUE THREAD

**Issue by kunli2** [openrewrite/rewrite-kotlin#207]
Would like to discuss this case, trailing semicolon is unnecessary but might exist in code.
Currently, the semicolon is dropped by the parser.
I think we might want to keep it in the parser but have a recipe to remove it.

An example
```java
    @Test
    void withUnneceesserySemicolon() {
        rewriteRun(
          kotlin(
            """
              val a = 1;
              val b = 2;
              """
          )
        );
    }
```

**Comment by traceyyoshima** [comment]
@kunli2  -- The semi-colons should be preserved, and it means that there is a missing `maybeSemiColon` to generate the rightPadded element.

**Comment by kunli2** [comment]
Thanks Tracey, fixed by https://github.com/openrewrite/rewrite-kotlin/pull/209
