### ISSUE TITLE
Bug parsing string literals with interpolation and slashes when passed as argument

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#231]
The following test fails:
```java
    @Test
    void stringArgumentWithSlashes() {
        rewriteRun(
          kotlin(
            """
              val a = 1
              print("a/b")
              """
          )
        );
    }
```

What gets printed back out is:
```
val a = 1
print("ab")///
```

**Comment by knutwannheden** [comment]
Not sure if we have to do anything, as the example given isn't valid (`print()` is not a declaration).

**Comment by traceyyoshima** [comment]
@knutwannheden What do you think about repurposing this issue to investigate how to implement the `Kotlin` compilers syntax analysis into the `KotlinParser`'s compiler configuration?

I looked into this briefly on Friday morning and found where the analysis occurs [here](https://github.com/JetBrains/kotlin/blob/master/compiler/cli/src/org/jetbrains/kotlin/cli/jvm/compiler/FirKotlinToJvmBytecodeCompiler.kt#L196).

The idea would be to add the analysis step and use the `AnalysisResult` to provide output in the tests. Additionally, it'll prevent these types of parse issues if we somehow parse code that won't compiler.

**Comment by knutwannheden** [comment]
With https://github.com/openrewrite/rewrite/commit/d7a1546ba20a2d74fc36a42ab27a67f87d69d36f the `Space#format()` function is now more permissive and will retain any `/` characters in the input which are not part of a comment delimiter. This way the returned `Space` can be used to retain parse-to-print idempotency.
