### ISSUE TITLE
Parser maps indexed access operator to `K.Binary`

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#233]
Currently the parser maps the indexed access operator to `K.Binary`. So the example

```kt
val arr = IntArray ( 1 )
val a = arr [ 0 ]
```

is translated to a `K.Binary` where the left is the identifier `a` and the right is the literal `0`.

I suspect it would make more sense to translate this [indexed access operator](https://kotlinlang.org/docs/operator-overloading.html#indexed-access-operator) to a method invocation (in this case to `kotlin.IntArray#get()`) which is the designated `get` operator or possibly something which would be similar to a Java array access.

For more complex examples with multiple parameters it should probably be a method invocation. E.g.

```kt
class Surface {
    operator fun get(x: Int, y: Int) = 2 * x + 4 * y - 10
}
fun getZValue(mySurface: Surface, xValue: Int, yValue: Int) =
    mySurface[xValue, yValue]
```

**Comment by traceyyoshima** [comment]
> @traceyyoshima What are your thoughts on this one?

@knutwannheden I agree entirely. I planned to add this in the `KBinary` changes before I got caught up in COBOL. This will be especially important for preserving the overloads in the LST.

The idea was to add `KArrayAccess,` `KUnary,` `KBinary,` or something along those lines for print idempotence.

**Comment by knutwannheden** [comment]
@traceyyoshima Something like `KArrayAccess` (or `KIndexedArrayAccess`) would work. Another potentially simpler alternative would be to map it to a `J.MethodInvocation` and add an `IndexedAccess` marker to it. I think that could have some nice advantages. In the following example
```kt
class Surface {
    operator fun get(x: Int, y: Int) = 2 * x + 4 * y - 10
}
val surface = Surface()
val z1 = surface[4, 2]
val z2 = surface.get(4, 2)
```
The initializers for `z1` and `z2` would map to the LST (except for the marker of course).

I will prepare a corresponding PR.
