### ISSUE TITLE
Support subject variable of when expression

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#240]
As [documented](https://kotlinlang.org/docs/control-flow.html#when-expression) a Kotlin when expression's subject can also be assigned to a variable as in the following test case:

```java
    @Test
    void subjectVariable() {
        rewriteRun(
          kotlin(
            """
              val x = when (val response = listOf(1, 2) as Collection<Int>) {
                  is List -> "l"
                  else -> ""
              }
              """
          )
        );
    }
```

Currently this parses but produces the wrong result when serialized again.

**Comment by knutwannheden** [comment]
The `val` statement could be nested in the `K.When`'s `J.ControlParentheses`, I am however unsure if that would be a good idea. The LST nesting would then look like:
```
K.When
  J.ControlParentheses
    K.StatementExpression
      J.VariableDeclarations
        J.VariableDeclarations$NamedVariable
```

What do you think, @traceyyoshima ? FWIW, in the FIR model the `FirWhenExpression` directly owns a `FirVariable` as the subject variable.

**Comment by knutwannheden** [comment]
I've pushed a commit to allow parsing (and printing) sources using this construct. That leaves us more time to decide on the LST model.

**Comment by traceyyoshima** [comment]
> What do you think, @traceyyoshima ?
> FWIW, in the FIR model the FirWhenExpression directly owns a FirVariable as the subject variable.

I agree with your decision, a `K.StatementExpression` is fine for now. We should focus on idempotent printing so that we have tests in place before making major changes. I suspect we'll be able to assess how to approach implementing a data-flow (only exists for J) compatible K tree after idempotent prints are accomplished.

I worry about the time and complexity to achieve idempotent prints if we handle all the compiler de-sugaring without tests in place. Since the backend of the Kotlin compiler that occurs after the FIR is converted to the IR (additional transformations to the tree to work on the JVM) is complicated.

**Comment by knutwannheden** [comment]
@traceyyoshima I am also wondering right now how this all relates to Java's pattern matching switch expression. Possibly it can be mapped directly to that? Although I don't know right now if Java has an equivalent to the subject variable.

**Comment by knutwannheden** [comment]
AFAICT Java's switch expression doesn't have any equivalent for the subject variable. So I guess we must stay with `K.When`.

**Comment by knutwannheden** [comment]
@traceyyoshima If we were to change `K.When#selector` from `ControlParentheses<Expression>` to `ControlParentheses<TypedTree>` (or `ControlParentheses<J>`) then it would also work when a subject variable is declared.

Using `ControlParentheses<J>` is probably safer. I assume there is a good reason that `Expression` doesn't extend `TypedTree`, but I don't know what it is. But there are a few types in `K` which implement only `Expression` and not `TypedTree`. This should probably be fixed at some point, but I don't see this as urgent.

I will prepare a PR. The only thing that changes is that then there is no longer any intermediate `K.StatementExpression` element below the `J.ControlParentheses`.
