### ISSUE TITLE
Issue with trailing comma in data classes

### ISSUE THREAD

**Issue by tobias-bahls** [openrewrite/rewrite-kotlin#247]
## What version of OpenRewrite are you using?
Open Rewrite Plugin `org.openrewrite.rewrite:6.1.26`
Module `org.openrewrite:rewrite-kotlin:1.4.0`

## How are you running OpenRewrite?
Gradle Plugin, simple configuration:

```
rewrite {
    activeRecipe("org.openrewrite.kotlin.cleanup.ImplicitParameterInLambda")
}
```

## What is the smallest, simplest way to reproduce the problem?

```kotlin
data class Test(attr: String,)
```

## What did you expect to see?
No error

## What did you see instead?
> There were problems parsing <file>.kt

## What is the full stack trace of any errors you encountered?
No stack trace is printed

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Potentially

**Comment by timtebeek** [comment]
Thanks for reporting this here @tobias-bahls and trying out rewrite-kotlin:1.4.0 on the day it came out. I imagine @knutwannheden would be the one to take this on.

**Comment by knutwannheden** [comment]
Yes, thanks for the report. Will look into this first thing tomorrow.

**Comment by tobias-bahls** [comment]
Thanks for the quick fix!
