### ISSUE TITLE
Name of function type parameters is not parsed

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#266]
[Function types](https://kotlinlang.org/docs/lambdas.html#function-types) can in Kotlin optionally specify parameter names:

```java
    @Test
    void namedParameter() {
        rewriteRun(
          kotlin(
            """
              val f: (p: Any) -> Boolean = { p -> true }
              """
          )
        );
    }
```
The parser does not yet support this and it results in a parse-to-print failure when encountered.

**Comment by traceyyoshima** [comment]
I think `K.FunctionType.Parameters` and removing the `J.Lambda` is reasonable. It'll likely prevent unexpected recipe changes from `J` as well.
