### ISSUE TITLE
Error parsing extension function call

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#270]
The following extension function call 
```kt
val block: Collection<Any>.() -> Unit = {}
val r = listOf("descriptor").block()
```
currently prints back out as
```kt
val block: Collection<Any>.() -> Unit = {}
val r = blocklistOf("descriptor").block()
```
Most likely the parser adds some marker which then misguides the printer.

**Comment by traceyyoshima** [comment]
I suspect this is caused by a condition failing to detect the select for the `block` function call.

**Comment by knutwannheden** [comment]
I don't see how we can use the FIR to derive this. I will read up on https://kotlinlang.org/spec/overload-resolution.html#receivers and see if that helps.

**Comment by knutwannheden** [comment]
It can be even more complicated when there are additional arguments, as the function call arguments effectively get split across three different locations:
```kt
val block2: Collection<Any>.(String, () -> Unit) -> Unit = { _, _ -> run {} }
val r2 = listOf("descriptor").block2("x") {}
```
I just now realize that the function type here in fact describes an extension function. I wasn't aware that also function types can describe extension functions. But this at least makes it consistent with the syntax and could possibly make it simpler to parse.

Makes me wonder how we account for extension functions (and what could even be anonymous functions as in `listOf("").(block2 as (Collection<Any>.(String, () -> Unit) -> Unit))("") {}`) in our `JavaType` type attribution...
