### ISSUE TITLE
Parse error on nullable parenthesized function type

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#275]
When parsing the [function type](https://kotlinlang.org/docs/lambdas.html#function-types) in
```kt
val v: ((Any) -> Any)? = null
```
what gets printed back out again is
```kt
val v: (Any)(Any) -> Any)? = null
```
It seems like the parser can't handle the parentheses which are there to make the type nullable.

**Comment by traceyyoshima** [comment]
FYI - The compiler removes Unnecessary parens, so the detection is attempted in `visitElement`. However, before the compile revision to access the PSI, there needed to be more information on the list parens. I handled a handful of cases manually and intended to remove all of that code, and I may have missed a few cases.

**Comment by knutwannheden** [comment]
As I think we've seen before, we need something like a `K.FunctionType` as this isn't really a lambda.
