### ISSUE TITLE
Parse error on parenthesized cast

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#276]
When parsing
```kt
val s = "s" as (String?)
```
it gets printed back out as
```kt
val s = "s" as String(String?)
```
Apparently the parser doesn't expect the type to be parenthesized in this context.

**Comment by knutwannheden** [comment]
Not sure how we should handle this one. `J.Parentheses` does not implement `TypeTree`. We could maybe add a marker? For now leaving it as-is, as I suspect this is pretty uncommon.

**Comment by kunli2** [comment]
noted this can be more complicated like this 
```kotlin
val b = "s" as? ( ( /*c1*/ (String ?) /*c2*/ ) )
```

**Comment by kunli2** [comment]
from the compiler's perspective, 
```kotlin
val b = "s" as ( ( /*c1*/ (String?) /*c2*/ ) )
```
is equivalent to
```kotlin
val b = "s" as String?
```

And the content before and after type `( ( /*c1*/ (` and `) /*c2*/ ) )` are treated like a comment, maybe we can have a marker to contains pre-text and post-text but not in comment format.

**Comment by traceyyoshima** [comment]
fixed by https://github.com/openrewrite/rewrite-kotlin/commit/21be273d6d47ec3879b6cfd281a39d3aff7332b8
