### ISSUE TITLE
Parsing error: Idempotent print issue on destructuring variable declaration with types

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#404]
```java
    @Test
    void destructuringWithTypes() {
        rewriteRun(
          kotlin(
            """
              fun example ( ) {
                val ( a : Int , b : String? ) = Pair ( 1 , "Two" )
              }
              """
          )
        );
    }
```

**Comment by kunli2** [comment]
`K.DestructuringDeclaration` does not have a space for variables type.
we may want to update `K.DestructuringDeclaration` model.
One option I can see is to change `K.DestructuringDeclaration#assignments;` from `JContainer<J.VariableDeclarations.NamedVariable>` type to `JContainer<Statement>` and each statement will be a `J.VariableDeclaration`.

@traceyyoshima @knutwannheden for insights.

**Comment by traceyyoshima** [comment]
> `K.DestructuringDeclaration` does not have a space for variables type. we may want to update `K.DestructuringDeclaration` model. One option I can see is to change `K.DestructuringDeclaration#assignments;` from `JContainer<J.VariableDeclarations.NamedVariable>` type to `JContainer<Statement>` and each statement will be a `J.VariableDeclaration`.
> 
> @traceyyoshima @knutwannheden for insights.

I think we should deprecate `JContainer<J.VariableDeclarations.NamedVariable> assignments;`, and make it nullable. Add the appropriate backward compatibility, then add `JContainer<Statement> destructAssignments;`. In most cases, we'll create a new `J.VariableDeclarations` like in `J.MethodDeclaration`. The `Statement` will allow us to handle any other cases that we may discover, and we have precedence for Statement containers already.

**Comment by kunli2** [comment]
yeah, agree, using `JContainer<J.VariableDeclaration>` or `JContainer<Statement>` both works for this case, but I concern that we may discover more cases that might require `JContainer<Statement>` in the future.
