### ISSUE TITLE
Class is not detected on the classpath

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#43]
Discovered in PR [here](https://github.com/nomisRev/rewrite-arrow/pull/4/commits/4e4832dc79ea3302c36f2c2941038650427e1412).

The class path is detected, the jar is set in `KotlinParser` through `addJvmClasspathRoot(compilerConfiguration, file);`, and the class exists in the jar, but the `Kotlin` compiler does not resolve the type.

**Comment by traceyyoshima** [comment]
@nomisRev :wave:, I may be wrong, but I think the issue is caused by the test.

The code for the shift function in the EffectScope class is:
```kotlin
public interface EffectScope<in R> {
    public fun <B> shift(r: R): B
}
```

AFAIK the function call `return scope.shift(false) { "failure" }` isn’t valid. Should this work?

Otherwise, it the recipe does work with:
```java
    @Test
    void addEnsureImportForRaiseExtensionFunction() {
        rewriteRun(
          kotlin(
            """
              package com.yourorg
                            
              import arrow.core.continuations.EffectScope

              fun test(scope: EffectScope<String>): Int {
                return scope.shift("failure")
              }
              """,
            """
              package com.yourorg
                            
              import arrow.core.Raise

              fun test(scope: Raise<String>): Int {
                return scope.shift("failure")
              }
              """
          )
        );
    }
```
There are two minor changes:
1. I updated the function call.
2. I updated the expected import from `arrow.core.raise.Raise` to `arrow.core.Raise` to match the recipe parameter.

What do you think?

**Comment by nomisRev** [comment]
Oof, you're absolutely right. Embarrassing.. Sorry you've wasted time on this.

Side-question: Would it be possible to show the compiler errors here? The output was quite confusing for me, and I incorrectly made the assumptions the code was fine.

**Comment by traceyyoshima** [comment]
> Oof, you're absolutely right. Embarrassing.. Sorry you've wasted time on this. Side-question: Would it be possible to show the compiler errors here? The output was quite confusing for me, and I incorrectly made the assumptions the code was fine.

No problem; I agree that output is deceptive. The compiler errors are intentionally swallowed [here](https://github.com/openrewrite/rewrite-kotlin/blob/main/src/main/java/org/openrewrite/kotlin/KotlinParser.java#L303). The compiler expect all the sources to be added to the [compiler input](https://github.com/openrewrite/rewrite-kotlin/blob/main/src/main/java/org/openrewrite/kotlin/KotlinParser.java#L278) before the FIRs are type attributed.

It might be possible to compile inputs one at a time using caching, but I'm not sure how to do that yet. Any FIR error reference implies a compilation failure, but it won't be specific until we figure out how to compile one input at a time.

Closing issue, since it's been resolved. Thanks for pioneering `rewrite-kotlin` :)
