### ISSUE TITLE
Parsing error: ClassCastException K$AnnotatedExpression cannot be cast to class org.openrewrite.java.tree.TypeTree

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#434]
TODO: reproduce

```
java.lang.ClassCastException: class org.openrewrite.kotlin.tree.K$AnnotatedExpression cannot be cast to class org.openrewrite.java.tree.TypeTree (org.openrewrite.kotlin.tree.K$AnnotatedExpression and org.openrewrite.java.tree.TypeTree are in unnamed module of loader org.openrewrite.gradle.RewriteClassLoader @458bb8f6)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitParameter(KotlinTreeParserVisitor.java:864)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitParameter(KotlinTreeParserVisitor.java:71)
  org.jetbrains.kotlin.psi.KtParameter.accept(KtParameter.java:51)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.mapParameters(KotlinTreeParserVisitor.java:3781)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitPrimaryConstructor(KotlinTreeParserVisitor.java:936)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitPrimaryConstructor(KotlinTreeParserVisitor.java:71)
  org.jetbrains.kotlin.psi.KtPrimaryConstructor.accept(KtPrimaryConstructor.kt:32)
  org.openrewrite.kotlin.internal.KotlinTreeParserVisitor.visitClass0(KotlinTreeParserVisitor.java:2092)
  ...
```

**Comment by kunli2** [comment]
I think `K.AnnotatedExpression` should be an `org.openrewrite.java.tree.TypeTree`.
since we created `K$AnnotatedExpression` for this [issue](https://github.com/openrewrite/rewrite-kotlin/issues/408).
so  `K.AnnotatedExpression` can be a wrapping of `J.ParameterizedType` or `J.Identifier`, so it should be `TypeTree`

**Comment by kunli2** [comment]
+ @knutwannheden for reference.

**Comment by knutwannheden** [comment]
Note: We initially added `K.AnnotatedExpression` in #281 to fix #267.

@kunli2 Can you show me an example of what leads to the exception? Please note that Java also supports stuff like `List<@Foo String>`, where `@Foo String` is represented by a `J.AnnotatedType`. So if it is types we want to annotate, I think it seems to be better to use the existing `J.AnnotatedType` instead.

**Comment by traceyyoshima** [comment]
Ah, `J.AnnotatedType` will fix the issue

**Comment by traceyyoshima** [comment]
Closing issue, this will be fixed by https://github.com/openrewrite/rewrite-kotlin/issues/408
