### ISSUE TITLE
Not running on commonMain of Kotlin Multiplatform Project

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#46]
Rewrite is not running over commonMain sourceSet of a KMP. Example PR: https://github.com/nomisRev/rewrite-arrow/pull/32.

Running `./gradlew build :sample:rewriteRun` shows that the sources in `sample/src/commonMain/kotlin/org/example/example.kt` are not being rewritten or updated.

**Comment by traceyyoshima** [comment]
Duplicate of https://github.com/openrewrite/rewrite-gradle-plugin/issues/172
