### ISSUE TITLE
AnnotationMatcher doesn`t work in kotlin

### ISSUE THREAD

**Issue by jeonyeonbin** [openrewrite/rewrite-kotlin#466]
Hi, i send bug report in rewrite-kotlin
While using AnnotationMatcher, I think I found a bug that doesn't work only in Kotlin.

If you check the JavaType when using Kotlin,
It appears as JavaType$Method, and when using java, it appears as JavaType$Class.

in AnnotationMatcher method matchesAnnotationName got false in kotlin.
can u help me?

<img width="1443" alt="image" src="https://github.com/openrewrite/rewrite-kotlin/assets/33460988/848fcf2c-e4de-45f7-9050-33ea693225d8">

**Comment by timtebeek** [comment]
That seems like a bug indeed; would you be open to creating a draft pull request that adds a test for this recipe here? That way we can run the above in a debugger from the unit test and look at what's needed for a fix.

**Comment by jeonyeonbin** [comment]
i add sample code in https://github.com/openrewrite/rewrite-kotlin/pull/467

**Comment by traceyyoshima** [comment]
Hi @jeonyeonbin, thank you for reporting the issue and providing a test -- we'll fix it shortly :)

**Comment by timtebeek** [comment]
Hi @jbellenger ; we typically do a full release train every two weeks or so, with occasional patch releases in between, provided there's no dependencies on upstream changes (which I think there might be just now). Tracey can probably best tell you if and when we can do a release of rewrite-kotlin specifically, and the downstream plugins following that. If you want to try this out in the meantime it's best to use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions). Hope that helps!
