### ISSUE TITLE
Parsing issue: Back ticks are preserved in identifier.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#479]
```
import java.lang.Integer.MAX_VALUE
val m = `MAX_VALUE`
```

**Comment by kunli2** [comment]
from PSI perspective, 
```
`MAX_VALUE`
```
is indeed an identifier, so I think it's fine.


```
    \---(35,54) | PROPERTY | KtProperty | Text: "val m = `MAX_VALUE`"
        |---(35,38) | val | LeafPsiElement | Text: "val"
        |---(38,39) | WHITE_SPACE | PsiWhiteSpaceImpl | Text: " "
        |---(39,40) | IDENTIFIER | LeafPsiElement | Text: "m"
        |---(40,41) | WHITE_SPACE | PsiWhiteSpaceImpl | Text: " "
        |---(41,42) | EQ | LeafPsiElement | Text: "="
        |---(42,43) | WHITE_SPACE | PsiWhiteSpaceImpl | Text: " "
        \---(43,54) | REFERENCE_EXPRESSION | KtNameReferenceExpression | Text: "`MAX_VALUE`"
            \---(43,54) | IDENTIFIER | LeafPsiElement | Text: "`MAX_VALUE`"
```

**Comment by knutwannheden** [comment]
I think we should add a `Quoted` marker for this purpose. Many languages have that concept.

**Comment by traceyyoshima** [comment]
> I think we should add a `Quoted` marker for this purpose. Many languages have that concept.

That sounds good -- I know this happens in `rewrite-javascript` as well, though I don't recall the rules for other languages off the top of my head.

That'll allow changes to occur on the identifier while preserving the escapes. And we could technically detect unnecessary escapes and remove them in a clean-up recipe.
