### ISSUE TITLE
Info to extend TypeValidation for Kotlin

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#482]
#### Code
```kotlin
@file:Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN", "unused")
```

#### Info on use-site name
A use-site annotation is a keyword that informs the compiler where to apply annotation.
The use-site annotation does not resolve to an annotation with a type, which means the type is null.
FindMissingTypes does not consider this case as a valid null type, which leads to an error.

#### Code
```kotlin
import java.util.regex.Pattern.CASE_INSENSITIVE as i
class A {
    val f = arrayOf(i)
}
```
#### Info
The variable type of a type aliases identifier is constructed from the aliased type. So, the aliased type and the J.Identifier's name do not match. The identifier `i` has a type of `java.util.regex.Pattern{name=CASE_INSENSITIVE,type=kotlin.Int}`

#### Code
```kotlin
val a = mapOf ( 1 to "one" , 2 to "two" )
val b = a [ 1 ]
```

#### Info on `get` and `set`
Kotlin recommends using `map[key]` instead of `map.get(key)`. The type associated with the `get` is a MethodType with the name `get`, which does not match the name of the method invocation created `a`. A similar issue happens with `set`.

#### Code
```kotlin
              abstract class Test ( arg : Test  .   ( )  ->   Unit    =  { } ) {
                  init {
                      arg ( )
                  }
              }
```
#### Info on `invoke`
A similar issue exists for implicit invoke calls.

#### Code
```kotlin
val positive = fun(i: Int) = i > 0 /* C */
```
#### Info on `anonymous functions`
Anonymous functions have the name `anonymous`, which does not match the identifier created with an empty name.

#### Code
```kotlin
              operator fun <T> MutableCollection<T>.divAssign(elements: Collection<T>) {
                  this.retainAll(elements)
              }
```
#### Info on receivers
An extension receiver has an unused name, `<receiverType>`, which does not match the variable type name.

#### Code
```kotlin
              import kotlin.text.Regex

              fun foo(choices: List<Pair<String, String>>, peekedHeader: Regex) {
                  for ((_, adapter) in choices) {
                      if (adapter.matches(peekedHeader)) {
                          print("1")
                      }
                  }
              }
```
#### Info on destructuring declarations
Similar to receivers, a destruct is created with a name `<destruct>`

### MemberReference
Null types on class literal expressions `Type::class`.
Type validation fails because the types are intentionally set to null [here](https://github.com/openrewrite/rewrite-kotlin/blob/main/src/main/java/org/openrewrite/kotlin/internal/KotlinTreeParserVisitor.java#L347).

**Comment by traceyyoshima** [comment]
@knutwannheden @kunli2 this is a list of conditions that differ from Java to augment the type validation for Kotlin. I'll be adding to the list as other issues are identified. Please feel free to add/remove/edit as you see fit.

**Comment by traceyyoshima** [comment]
@knutwannheden @kunli2 is a list of errors thrown after type validation is added to Assertions#kotlin, which I think should be added as acceptable types.

Do you think there are any cases, which should be considered acceptable?

**Comment by knutwannheden** [comment]
I am not sure I understand the question correctly.

Please also note that the TypeAlias example is an import alias and not a type alias. Of course the import alias can also be used to alias type names, but this is still distict from `typealias`.
