### ISSUE TITLE
PSI to FIR association issue: Incorrect on parent classes.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#517]
```kotlin
                  class A {
                      class B {
                          class C
                      }
                  }
                  val c = A.B.C()
```

Both A and B will have the same type, `A$B`.

**Comment by kunli2** [comment]
This is hard to resolve since `A.B` is the minimum granularity in the FIR, so to distinguish between `A` and `B` will require some additional algorithm on the FIR.
