### ISSUE TITLE
Imports/Import aliases do not contain type attribution, because it is not available in the FIR.

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-kotlin#53]
This issue is meant to track discovery on if it is possible and how we may add type-attribution to imports.

The FIR does not contain any type attribution on imports, so imports and the aliases contain null type attribution.

**Comment by nomisRev** [comment]
Hey @traceyyoshima,

I asked a colleague that work with FIR, and the compiler a lot. Not sure if it helps you in any way.

We can perhaps try to make some time in the future to contribute (I know he's quite busy/overloaded with other efforts atm). Or maybe we can try setting up a call, so we can discuss some ideas / share some knowledge around this ☺️
And he replied this:

> The Kotlin compiler has full knowledge of resolved type aliases and all the info around them [https://github.com/JetBrains/kotlin/blob/f3fd4b3e0186473b38982d758e330dec7929147c/[…]/tree/gen/org/jetbrains/kotlin/fir/declarations/FirTypeAlias.kt](https://github.com/JetBrains/kotlin/blob/f3fd4b3e0186473b38982d758e330dec7929147c/compiler/fir/tree/gen/org/jetbrains/kotlin/fir/declarations/FirTypeAlias.kt#L33) in the FIR level.
At first glance and assuming it's here where he builds type signatures and type related stuff [https://github.com/openrewrite/rewrite-kotlin/blob/9fe71524e8236bc0b4e0f837a32b543[…]ain/java/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.java](https://github.com/openrewrite/rewrite-kotlin/blob/9fe71524e8236bc0b4e0f837a32b543879d3c4f2/src/main/java/org/openrewrite/kotlin/KotlinTypeSignatureBuilder.java) he currently has no code that handles FirTypeAlias

> A Type Alias itself it's a type of top level declaration only but a type that refers to a type alias can be handled in all those positions.
Also you can ask the type alias what the abbreviation is and what the type args etc are as you can see in that class.

cc\\ @raulraja

**Comment by traceyyoshima** [comment]
fixed by https://github.com/openrewrite/rewrite-kotlin/commit/a5553aa20765b165c35716c8bcee2c98cfaeaf6c
