### ISSUE TITLE
AddImport static import

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#54]
Based on our original discussion in https://github.com/openrewrite/rewrite-kotlin/issues/45#issuecomment-1474301327.
And on Slack: https://rewriteoss.slack.com/archives/C01AB6L98TC/p1679929779305809?thread_ts=1679927703.722339&cid=C01AB6L98TC

Updated in PR on arrow-rewrite: https://github.com/nomisRev/rewrite-arrow/pull/43.

Following change:

```diff
maybeAddImport("arrow.core.raise.ensure", false);
maybeAddImport("arrow.core.raise.RaiseKt", "ensure", false);
```

resulted in an incorrect change of formatting. The "static" import, is excluded from the regular import list, and follows a similar pattern of styling as Java imports. Which is unnatural for Kotlin, since there is no concept of "static" they also don't appear separately in the import list.

Strangely, it also resulted in the import getting collapsed into `*` imports when 3 of these "static" imports appeared. This was also an unexpected side-effect but could potentially be solved within the same issue.

When I didn't use "static" imports for these imports, I encountered an other issue. Since it was fixed by using "static" imports for these top-level imports I am assuming I was using a hack before by using `maybeAddImport("arrow.core.raise.ensure", false)` and this somehow caused a bug.

**Comment by knutwannheden** [comment]
@nomisRev We have now fixed this bug and it is available in the latest 1.3.4 release.
