### ISSUE TITLE
TabsAndIndentVisitor misbehaves when visiting annotations individually

### ISSUE THREAD

**Issue by nmck257** [openrewrite/rewrite-kotlin#546]
## What version of OpenRewrite are you using?

I am using

- OpenRewrite v8.11.1
- rewrite-kotlin v1.8.1

## How are you running OpenRewrite?

RewriteTest

## What is the smallest, simplest way to reproduce the problem?

```java
@Test
void foo() {
    rewriteRun(
            spec -> spec.recipe(RewriteTest.toRecipe(() -> new KotlinIsoVisitor<>() {
                @Override
                public J.Annotation visitAnnotation(J.Annotation annotation, ExecutionContext executionContext) {
                    J.Annotation a = super.visitAnnotation(annotation, executionContext);
                    return autoFormat(a, executionContext);
                }
            })).parser(KotlinParser.builder().logCompilationWarningsAndErrors(true)),
            kotlin("""
                    package org.sample
                    
                    @SafeVarargs
                    @SuppressWarnings
                    class Foo {
                        val x =
                            3.plus(
                                3
                            )
                    }
                    """
            ));
}
```

## What did you expect to see?

Success

## What did you see instead?

```
org.opentest4j.AssertionFailedError: [The recipe must not make changes to "openRewriteFile.kt"] 
expected: "package org.sample

@SafeVarargs
@SuppressWarnings
class Foo {
    val x =
        3.plus(
            3
        )
}"
 but was: "package org.sample

@SafeVarargs
    @SuppressWarnings
class Foo {
    val x =
        3.plus(
            3
        )
}"
```

## What is the full stack trace of any errors you encountered?

N/A

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I probably could, if it feels like a low-priority which y'all aren't eager to fix.

The test case probably seems a bit contrived, but, an existing `rewrite-spring` recipe (`ReplaceExtendWithAndContextConfiguration`) does it:
https://github.com/openrewrite/rewrite-spring/blob/847804059e1b568026a155cb17f3e732ad2fe6be/src/main/java/org/openrewrite/java/spring/boot2/ReplaceExtendWithAndContextConfiguration.java#L96

Arguably, that recipe is autoformatting a bit over-eagerly, but I think the scenario discovered here is still valid.

**Comment by timtebeek** [comment]
Really helpful to have the test provided, and a link to the Spring recipe that shows it's not an edge case. I'd say this is still a very valid one to pick up, as we should not create any unnecessary output changes. Help would be appreciated if possible!
