### ISSUE TITLE
Add new `K.TypeAlias` element

### ISSUE THREAD

**Issue by knutwannheden** [openrewrite/rewrite-kotlin#550]
Type aliases are currently modelled as variable declarations with a special `typealias` modifier on them. While this works syntactically, it doesn't make much sense from a model perspective, as a `typealias` doesn't really introduce a new variable and as such would end up confusing a lot of existing recipes. Instead, there should be a dedicated `K.TypeAlias` model element for this.

**Comment by knutwannheden** [comment]
Please also see https://github.com/openrewrite/rewrite-kotlin/pull/549/commits/12f31a05ab935d5e95b89c905f60d7333d253f23 where I removed some legacy handling of `typealias`. It looks like we at some point had a dedicated `typealias` annotation instead.

**Comment by traceyyoshima** [comment]
PR is pending a decision on how to represent the whitespace, comments, and annotations before the keyword `typealias`.
