### ISSUE TITLE
Issue with change type on an annotation with a use site target

### ISSUE THREAD

**Issue by rogerpeckham-toast** [openrewrite/rewrite-kotlin#576]
## What version of OpenRewrite are you using?

I am using

- Gradle plugin v6.6.3
- rewrite-kotlin v1.8.4

## How are you running OpenRewrite?

I am using the Gradle plugin to run ChangeType recipes.

## What is the smallest, simplest way to reproduce the problem?

I have created the test [here](https://github.com/rogerpeckham-toast/rewrite-kotlin/blob/change_type_issue/src/test/java/org/openrewrite/kotlin/ChangeTypeTest.java#L488C9-L488C9). The test is a change type recipe for an annotation class that is used with a use site target. When run the import is not added for the new `Target` annotation. 

After stepping through the code I am starting to believe that for some reason the `AddImport` visitor is not actually causing the issue because when the type is changed the underlying type in use isn't changed. To explain using the annotations from the linked test, it doesn't add an import for the `Target` annotation because it thinks that the `Target` annotation added actually has the type `a.b.Original`.

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

If I figure out the source of this issue I might be able to fix it but there is a good chance I will not be able to fix it.

**Comment by knutwannheden** [comment]
This has now been fixed and will be included in the next release. You can expect a new release within the next two weeks. In the mean time you can use snapshot builds, which should already be available.
