### ISSUE TITLE
Rewriting lambda based code, related to #25

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#59]
Hey @traceyyoshima,

You mentioned that I could open a ticket for a kind-of rewrite I am struggling with. Beside the `ValidatedNel` typealias rewrite, there is one more kind of recipes that I am struggling with. If both are resolved I think I can provide rewrites for all important rewrites needed for Arrow, which would be huge 🥳

It's kind-of related to to #25, since that would also solve my problem but I think applying `ReplaceWith` through recipes is even more complex. I am not sure if the Kotlin compiler/parser somewhere exposes `ReplaceWith` rewrites (this could be possible). It should occurs somewhere in the Kotlin Plugin / analyser. (I request some pointers from @raulraja if he could provide more insights).

Here is an example of a `ReplaceWith` in action:

https://user-images.githubusercontent.com/12424668/229137115-30ff6093-d78b-4f77-84db-be71b9450496.mov

And there is the relevant code in Arrow:

https://github.com/arrow-kt/arrow/blob/4dfdd628bd5a1cce2fb65e93b31ac6e65c5fffb3/arrow-libs/core/arrow-core/src/commonMain/kotlin/arrow/core/Either.kt#L1995

To give another example:

```kotlin
fun validate(int: Int): Validated<String, Int> = TODO()

listOf(1, 2, 3).traverse { validate(it) }
```

Should be rewritten to:

```kotlin
fun validate(int: Int): Either<String, Int> = TODO()

listOf(1, 2, 3).mapOrAccumulate { validate(it).bind() }
```

What I am struggling with is how this rewrite can be achieved in a recipe. The biggest problem I think is that the lambda can also appear in the shape of a method reference: `listOf(1, 2, 3).traverse(::validated)` or be a multi-line lambda. So it seems that the only shaped approach is to capture the result of the lambda in a `val` and then call `bind` in the following line.

```kotlin
fun validate(int: Int): Either<String, Int> = TODO()

listOf(1, 2, 3).mapOrAccumulate {
  val res = validate(it)
  res.bind()
}
```

That requires to know for sure the chosen name for `res` doesn't overlap with any other variables defined in a potentially multi-line lambda.

Hence the complexity of this recipe. Any insights, ideas, or contributions to https://github.com/nomisRev/rewrite-arrow would of course also be super appreciated.

**Comment by traceyyoshima** [comment]
@nomisRev the cases look pretty straight forward to cover, but I'm not sure about covering all the edge cases. Do you have example of what you'd expect `listOf(1, 2, 3).traverse(::validated)` to be changed to?

**Comment by nomisRev** [comment]
Probably the same,

```kotlin
listOf(1, 2, 3).mapOrAccumulate {
  val res = validate(it)
  res.bind()
}
```

If it can be done without the intermediate `val res` then even better.

**Comment by traceyyoshima** [comment]
@nomisRev I added an example of how the transformation may be done to a fork of rewrite-arrow.
I think the issue may be closed in favor of the branch + OpenRewrite slack for any follow-up questions.
What do you think?

**Comment by nomisRev** [comment]
Hey @traceyyoshima,
Sorry for the late reply. Yes, let's merge this issue in favour of the merged recipe and actual issues that come up. Thank you for all the support and help ☺️ 

PS: Thanks @timtebeek for assigning me again 😅
