### ISSUE TITLE
UpgradeSpringBoot_3_2 recipe for Kotlin

### ISSUE THREAD

**Issue by sk-saha** [openrewrite/rewrite-kotlin#596]
## What problem are you trying to solve?
Upgrade Kotlin Spring Boot projects to 3.2.x

## Have you considered any alternatives or workarounds?
org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2
Did not really work.

**Comment by timtebeek** [comment]
Let's continue this on
- https://github.com/openrewrite/rewrite-spring/issues/498
