### ISSUE TITLE
Suspend lambda incorrectly rewrites return type

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#60]
When using the _special_ syntax for `suspend` lambdas without arguments `suspend { }` , the return type is incorrectly changed.

```kotlin
fun method ( ) {
    val lambda: suspend ( ) -> Int = suspend { 1 }
}
```

Results in:

```text
expected: 
  "fun method ( ) {
      val lambda: suspend ( ) -> Int = suspend { 1 }
  }"
 but was: 
  "fun method ( ) {
      val lambda:  Int = suspend { 1 }
  }"
```

**Comment by traceyyoshima** [comment]
fixed by https://github.com/openrewrite/rewrite-kotlin/commit/7c4cdcb3350bab8bdac599c7fdcdbebd43c9a88f
