### ISSUE TITLE
Parser error - lambda modifiers

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#70]
When parsing a lambda marked with a _lambda modifier_ it erases the lambda for the return type of the lambda.

```console
expected: 
  "inline fun example(
    noinline /* or crossinline */ block: () -> Unit
  ): Unit = Unit"
 but was: 
  "inline fun example(
    block Unit
  ): Unit = Unit"
```

**Comment by traceyyoshima** [comment]
@nomisRev quick note: I'm unsure if leading with multiple modifiers on a lambda is possible, so the API only supports one modifier now.

Changes:
https://github.com/openrewrite/rewrite-kotlin/commit/ed07afbebfa7db7f42d99f32c85c7282b694718b

**Comment by nomisRev** [comment]
@traceyyoshima it cannot lead with multiple modifiers, but it can with both `suspend` and `crossinline`. Will write a test case today to check if that works or not.

Thanks for all the quick fixes 🙌

**Comment by nomisRev** [comment]
Update, this work fine. It actually doesn't appear in the modifier list for lambdas.

```kotlin
suspend inline fun example (
  crossinline block : suspend ( ) -> Unit
) : Unit = Unit
```
