### ISSUE TITLE
Parser error - property delegation

### ISSUE THREAD

**Issue by nomisRev** [openrewrite/rewrite-kotlin#76]
The parser fails on property delegation.

```console
expected: 
  "class Test {
      val value by lazy { 10 }
  }"
 but was: 
  "class Test {
      val value get()by lazy { 10 }
  }"
```

**Comment by traceyyoshima** [comment]
Putting the issue aside for now since the fix will require some thought.
The issue is `by` and `lazy` is sugar for a lazy init to `getValue` the compiler has already applied desugaring so this may only be detected through the source code.
